export interface User {
    id : string;
    act1: boolean,
      act2: boolean,
      act3: boolean,
      actOther: string,
      eat1: boolean,
      eat2: boolean,
      eat3: boolean,
      eat4: boolean,
      eat5: boolean,
      eat6: boolean,
      eatOther: string,
      drink1: boolean,
      drink2: boolean,
      drink3: boolean,
      drink4: boolean,
      drinkOther: string,
      alco1: boolean,
      alco2: boolean,
      alco3: boolean,
      alco4: boolean,
      alco5: boolean,
      alcoOther: string,
}